controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robot_shoulder_pan_joint
      - robot_shoulder_lift_joint
      - robot_elbow_joint
      - robot_wrist_1_joint
      - robot_wrist_2_joint
      - robot_wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper_finger_joint
      - gripper_right_outer_knuckle_joint